import '@/styles/globals.css';

import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';
import ProfileMenu from '@/components/navbar/ProfileMenu';
import NavMenu from '@/components/navbar/NavMenu';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <header className="bg-white shadow dark:bg-gray-800">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex h-16 items-center">
              <div className="flex w-full items-center justify-between">
                <h1 className="text-2xl font-bold text-gray-800 dark:text-white">GymTrack</h1>
                <NavMenu />
                <ProfileMenu />
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
