import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import {
  BarChart,
  Dumbbell,
  Calendar,
  ClipboardList,
  type LucideIcon,
} from "lucide-react";
import ProfileMenu from "@/components/navbar/ProfileMenu";

type NavItem = {
  href: string;
  icon: LucideIcon;
  label: string;
};

const navItems: NavItem[] = [
  { href: "/", icon: BarChart, label: "Dashboard" },
  { href: "/workouts", icon: ClipboardList, label: "Workouts" },
  { href: "/exercises", icon: Dumbbell, label: "Exercises" },
  { href: "/schedule", icon: Calendar, label: "Schedule" },
];

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <header className="bg-white shadow dark:bg-gray-800">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="flex h-16 items-center">
              <div className="flex items-center justify-between w-full">
                <h1 className="text-2xl font-bold text-gray-800 dark:text-white">
                  GymTrack
                </h1>
                <nav className="hidden space-x-4 md:flex">
                  {navItems.map((item) => (
                    <a
                      key={item.href}
                      href={item.href}
                      className={
                        "flex items-center rounded-md px-3 py-2 text-sm font-medium text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700"
                      }
                      //   ${
                      //   currentPage === item.label.toLowerCase()
                      //     ? "bg-gray-200 text-gray-800 dark:bg-gray-700 dark:text-gray-300"
                      //     : "text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700"
                      // }`
                    >
                      <item.icon className="mr-2 h-5 w-5" />
                      {item.label}
                    </a>
                  ))}
                </nav>
                <ProfileMenu />
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}

// return (
//   <div className={`min-h-screen ${darkMode ? "dark" : ""}`}>
//     <div className="flex h-screen flex-col bg-gray-50 dark:bg-gray-900">
//       {/* Top Navigation */}

//       {/* Main Content */}
//       <main className="flex-1 overflow-y-auto bg-white p-8 dark:bg-gray-900">
//         <div className="mx-auto max-w-7xl">{children}</div>
//       </main>
//     </div>
//   </div>
// );
